CREATE TABLE `sail_shop_product` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `handler` varchar(255) NOT NULL DEFAULT '' COMMENT '产品标题字符串索引',
  `handler_origin` varchar(255) NOT NULL DEFAULT '' COMMENT '产品标题字符串索引原始值',
  `shop_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '商店唯一ID',
  `title` varchar(255) NOT NULL DEFAULT '' COMMENT '商品标题',
  `price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '商品价格',
  `compare_at_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '对比价格',
  `default_sku_code` varchar(256) NOT NULL DEFAULT '' COMMENT '默认的SKU',
  `body_html` mediumtext COMMENT '商品描述',
  `image_ids` varchar(3000) NOT NULL DEFAULT '' COMMENT '产品图片id集合，按逗号拼接',
  `image_tmp_urls` text,
  `default_image_id` int(11) NOT NULL DEFAULT '0' COMMENT '产品主图',
  `default_image_tmp_url` varchar(512) DEFAULT '',
  `attribute` text COMMENT '产品属性，json格式',
  `count_skus` int(11) NOT NULL DEFAULT '0' COMMENT 'SKU数量统计(不包括系统生成的默认sku)',
  `is_logistics` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否需要物流运送',
  `weight` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '产品重量',
  `weight_unit` varchar(255) NOT NULL DEFAULT '' COMMENT '产品重量单位',
  `published_at` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '发布时间',
  `is_del` tinyint(3) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '上架状态(1:上架;2:下架;)',
  `sort` bigint(20) NOT NULL DEFAULT '0' COMMENT '排序，越大越靠前',
  `is_show_comment` tinyint(3) NOT NULL DEFAULT '0',
  `is_use_stock` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否启用库存',
  `soldout_policy` enum('Y','N') DEFAULT 'Y' COMMENT '售罄策略(Y:无库存继续出售;N:无库存不能出售)',
  `product_stock` int(11) NOT NULL DEFAULT '0' COMMENT '商品库存',
  `comments` bigint(20) NOT NULL DEFAULT '0' COMMENT '评论总数',
  `scores` bigint(20) NOT NULL DEFAULT '0' COMMENT '评分总数',
  `seo_title` varchar(255) NOT NULL DEFAULT '' COMMENT 'SEO标题',
  `seo_desc` varchar(1024) NOT NULL DEFAULT '' COMMENT 'SEO描述',
  `source` varchar(20) DEFAULT NULL COMMENT '导入来源',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_read` tinyint(11) NOT NULL DEFAULT '0' COMMENT '产品导入 先判定是否已经读取 1读取 2未读取',
  `count_sales` int(11) NOT NULL DEFAULT '0' COMMENT '销量',
  `youtube_video_url` varchar(255) NOT NULL DEFAULT '' COMMENT 'youtube视频地址',
  `youtube_video_pos` char(100) NOT NULL DEFAULT '' COMMENT 'youtube视频所在轮播图中位置',
  `sub_title` varchar(400) NOT NULL DEFAULT '' COMMENT '副标题',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_product_handler` (`shop_id`,`handler`),
  KEY `index_shop_id_handler` (`shop_id`,`handler`),
  KEY `index_shop_id_title` (`shop_id`,`title`),
  KEY `index_shop_id_del` (`shop_id`,`is_del`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=60104707 DEFAULT CHARSET=utf8mb4 COMMENT='产品基本信息表';